apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::973428414381:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-jObnxNoEgBjX
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - default-trainee
      userarn: arn:aws:iam::111122223333:user/admin
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2025-03-17T05:33:42Z"
  name: aws-auth
  namespace: kube-system
  uid: 71580cb5-edfd-43c3-960f-990f813d2a61
